environment:
  environment : "Snake"
  n_environments : 1
  render_mode : "rgb_array"
  difficulty : 2
  observation_type : "grid"
  n_actions : 4
  reward_food: 20
  reward_death: -5
  reward_step: -0.5

policy:
  network : "AttentionDQN"
  horizon : 1
  reward_discount : 0.995
  epsilon_strategy : "EpsilonGreedy"
  epsilon_start : 1.0
  epsilon_end : 0.
  epsilon_coeff : 0.99

policy-network:
  input_dim : 400
  output_dim : 4
  num_attention_layer : 2
  attention_layer_params : [{"num_heads" : 4}, {"num_heads" : 8}]
  num_fc_layer : 2
  dim_fc_layer : [16, 32]

policy-loss:
  loss : "MSELoss"

training:
  device : "cpu"
  optimizer : "Adam"
  lr_init : 0.001
  lr_scheduler : "ExponentialLR"
  lr_step_size : 10
  lr_gamma : 0.99
  n_epochs : 5
  n_episodes : 1000

save:
  checkpoint : 500
  save_model : True
  save_path : "./src/policy/models/attention-dqn/"

pretrain:
# network_model_path : "PUT-HERE-SOME-PATH.PT"