#!/bin/bash
#SBATCH --job-name=snake_game
#SBATCH --output=logs/%x_%j.out
#SBATCH --error=logs/%x_%j.err
#SBATCH --time=00:10:00
#SBATCH --partition=dcgp_usr_prod
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH --account=uts26_tornator_0

# ---- setup environment ----
module load python/3.11.7

# activate venv
source $SCRATCH/e2e-jepa/.venv/bin/activate

# go to project directory
cd $CINECA_SCRATCH/e2e-jepa

# ensure logs folder exists
mkdir -p logs

# ---- run program ----
python -m src.game.snake --difficulty 3 --render_mode rgb_array --registration
