#!/bin/bash
#SBATCH --job-name=e2e_train
#SBATCH --output=logs/%x_%j.out
#SBATCH --error=logs/%x_%j.err
#SBATCH --time=00:10:00
#SBATCH --partition=boost_usr_prod
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=128G
#SBATCH --account=uts26_tornator
#SBATCH --gres=gpu:1

# ---- setup environment ----
module load python/3.11.7
module load cuda/12.6
# activate venv
source $SCRATCH/e2e-jepa/.venv/bin/activate

# go to project directory
cd $SCRATCH/e2e-jepa

# ensure logs folder exists
mkdir -p logs

# ---- run program ----
python -m src.train.train --where ./models/exp2.pkl --config ./configs/raw-policies/dqn-conv-train.yaml
