environment:
  environment : "Snake"
  render_mode : "rgb_array"
  difficulty : 2
  observation_type : "grid"
  n_actions : 4
  reward_food: 20
  reward_death: -5
  reward_step: -0.5

policy:
  network : "AttentionPPO"
  horizon : 256
  reward_discount : 0.995
  epsilon_strategy : "EpsilonConstant"
  epsilon_start : 1.0
  epsilon_end : 0.
  epsilon_coeff : 0.99

policy-network:
  input_dim : 400
  output_dim : 4
  num_attention_layer : 2
  attention_layer_params : [{"num_heads" : 4}, {"num_heads" : 16}]
  num_fc_layer : 2
  dim_fc_layer : [16, 32]

policy-loss:
  loss : "PPOLoss"
  actor_coef : 0.01
  critic_coef : 0.5

training:
  device : "cpu"
  optimizer : "Adam"
  lr_init : 0.05
  lr_scheduler : "StepLR"
  lr_step_size : 10
  lr_gamma : 0.05
  loss : "PPOLoss"
  n_epochs: 5
  n_episodes: 1000

pretrain:
# network_model_path : "PUT-HERE-SOME-PATH.PT"